# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0026_auto_20180604_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='cta',
            name='description_de',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Body (richtext) of component', null=True),
        ),
        migrations.AddField(
            model_name='cta',
            name='description_en',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Body (richtext) of component', null=True),
        ),
        migrations.AddField(
            model_name='cta',
            name='description_es',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Body (richtext) of component', null=True),
        ),
        migrations.AddField(
            model_name='cta',
            name='description_fr',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Body (richtext) of component', null=True),
        ),
        migrations.AddField(
            model_name='cta',
            name='description_pl',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Body (richtext) of component', null=True),
        ),
        migrations.AddField(
            model_name='cta',
            name='description_pt',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Body (richtext) of component', null=True),
        ),
        migrations.AddField(
            model_name='cta',
            name='header_de',
            field=models.CharField(blank=True, help_text='Heading that will display on page for this component', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cta',
            name='header_en',
            field=models.CharField(blank=True, help_text='Heading that will display on page for this component', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cta',
            name='header_es',
            field=models.CharField(blank=True, help_text='Heading that will display on page for this component', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cta',
            name='header_fr',
            field=models.CharField(blank=True, help_text='Heading that will display on page for this component', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cta',
            name='header_pl',
            field=models.CharField(blank=True, help_text='Heading that will display on page for this component', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cta',
            name='header_pt',
            field=models.CharField(blank=True, help_text='Heading that will display on page for this component', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cta',
            name='name_de',
            field=models.CharField(default='', help_text='Identify this component for other editors', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cta',
            name='name_en',
            field=models.CharField(default='', help_text='Identify this component for other editors', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cta',
            name='name_es',
            field=models.CharField(default='', help_text='Identify this component for other editors', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cta',
            name='name_fr',
            field=models.CharField(default='', help_text='Identify this component for other editors', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cta',
            name='name_pl',
            field=models.CharField(default='', help_text='Identify this component for other editors', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cta',
            name='name_pt',
            field=models.CharField(default='', help_text='Identify this component for other editors', max_length=100, null=True),
        ),
    ]
